name: 'cowJacket_dbt_cloud'  # change this to your project name
version: '1.0.0'
config-version: 2

profile: 'default'  # or your profile name if using CLI

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


models:
  cowJacket_dbt_cloud:
    +materialized: table
    dim: 
        +materialized: table
    src:
        +materialized: ephemeral